name: Build and Push Docker image to GCR

on:
  push:
    branches:
      - v1.0.0

env:
  PROJECT_ID: microrts-sample
  IMAGE: microrts.api
  TAG: 1.0.0

jobs:
  setup-build-publish:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GKE_SA_KEY }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ env.TAG }}

